# 
# Workflow that sign and deploy the Android app the the internal beta channel of Google Play Console
# 

name: Sign and deploy

## Event triggers
on:
  workflow_call:


jobs:

  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Decrypt release keystore and release properties file from github secrets
      - name: Decrypt files
        id: decrypt_files
        run: |
          echo "Decrypting files..."

          echo "${{ secrets.FASTLANE_ENVIROMENT_CONTENT }}" > .env.default.asc

          gpg -d --passphrase "${{ secrets.FASTLANE_ENVIROMENT_PASSWORD }}" --batch .env.default.asc > .env.default

          echo "${{ secrets.RELEASE_KEYSTORE_CONTENT }}" > public_keystore.jks.asc

          gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" --batch public_keystore.jks.asc > app/public_keystore.jks

          echo "${{ secrets.SERVICE_ACCOUNT_GOOGLE_DEVELOPER_CONTENT }}" > service-account-google-developer.json.asc

          gpg -d --passphrase "${{ secrets.SERVICE_ACCOUNT_GOOGLE_DEVELOPER_PASSWORD }}" --batch service-account-google-developer.json.asc > service-account-google-developer.json
          
          echo "Finished decrypting files"

      # Set up ruby
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      # Gem caching
      - name: Gem caching
        id: gem_cache
        uses: actions/cache@v2
        continue-on-error: true
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Installing bundler to use fastlane on the machine
      - name: Setup fastlane
        id: set_up_fastlane
        run: |
          gem install bundler:2.3
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # Gradle cache
      - name: Cache Gradle packages
        id: cache_gradle_packages
        uses: actions/cache@v2
        continue-on-error: true
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}

      # Use fastlane to sign and upload the app
      - name: Sign and upload
        id: sign_and_upload
        run: bundle exec fastlane build