// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIGahDuMhg3CN5MSji4t4pjt9I37NnMtY',
    appId: '1:79656633282:web:76894fb2f9da9bf0008c5b',
    messagingSenderId: '79656633282',
    projectId: 'posadafy',
    authDomain: 'posadafy.firebaseapp.com',
    storageBucket: 'posadafy.appspot.com',
    measurementId: 'G-24MFX618MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk92YyM4HBwUhVbBxrDOC8il1uW9uMe7Y',
    appId: '1:79656633282:android:076597f2d34680b5008c5b',
    messagingSenderId: '79656633282',
    projectId: 'posadafy',
    storageBucket: 'posadafy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfGSNRBdVILPb1gLIO0L32fKmT8jy7DpY',
    appId: '1:79656633282:ios:36a874d6f98f12f6008c5b',
    messagingSenderId: '79656633282',
    projectId: 'posadafy',
    storageBucket: 'posadafy.appspot.com',
    iosClientId: '79656633282-9h6hvo7vva5ic525vsjs2dkdp2sbjl53.apps.googleusercontent.com',
    iosBundleId: 'com.example.takeABreak',
  );
}
