# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    sh "echo flutter test"
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

  end

  desc "Create an assemble bundle for release"
  lane :build do
    sh "echo flutter build appbundle"
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    build
    upload_to_play_store(track: ENV["upload_to"],
      skip_upload_apk: true, # Uploading only aab
    	skip_upload_metadata: true,
	    skip_upload_changelogs: true,
	    json_key: ENV["json_key"]
    )
  end
end
