# 
# Workflow that run the unit test and generate an output in case the test were sucessfully
# 

name: Unit tests

## Event triggers
on:
  workflow_call:
    

jobs:

  unit_tests_job:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.unit_tests_step.result }}
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.3'
      
      - run: flutter pub get

      - run: |
          if flutter test; then
            echo "All tests passed! "
            exit 0
          else
            echo "Something went wrong :c"
            exit 1
          fi
          echo "Workflow check finished"
