# 
# This wrokflow will run on every pull request to the develop branch
# 

name: Keeper workflow

## Actions that will be executed on
on:  
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  
  # 
  # chek.yml workflow
  # Run everity time in this workflow and generate an output in case the test were sucessfully
  # 
  # check:
  #   uses: ./.github/workflows/check.yml


  # # 
  # # deploy.yml
  # # Run if the pull request has the tag release and the output of the check.yml workflow is succesfully
  # # 
  # deploy:
  #   if: ((github.event.pull_request.merged == true) && (contains(github.ref, 'refs/tags/')))
  #   needs: check
  #   uses: ./.github/workflows/deploy.yml
  #   secrets: inherit

  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Decrypt files
      id: decrypt_files
      run: |
        echo "Decrypting files..."
        echo "$(pwd)"
        echo "$(ls -R)"
        echo "${{ secrets.KEY_PROPERTIES_CONTENT }}" > android/key.properties

        echo "${{ secrets.SERVICE_ACCOUNT_GOOGLE_DEVELOPER_CONTENT }}" > android/service-account-google-developer.json

        echo "${{ secrets.UPLOAD_KEYSTORE_CONTENT }}" > android/app/upload-keystore.jks

        echo "${{ secrets.ENV_DEFAULT_CONTENT }}" > .env.default
        echo "$(ls -R)"
        echo "Finished decrypting files"
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.3'
    - run: flutter pub get
    - run: flutter test
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.3'
    - run: flutter pub get
    - run: flutter test
    - run: |
        echo "$(ls -R)"
        flutter build appbundle

    - uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_GOOGLE_DEVELOPER_CONTENT }}
        packageName: com.exolimit.posadafy
        releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
        track: production
        status: inProgress
        inAppUpdatePriority: 2
        userFraction: 0.33
        whatsNewDirectory: distribution/whatsnew
        mappingFile: android/app/build/outputs/mapping/release/mapping.txt