# 
# This wrokflow will run on every pull request to the develop branch
# 

name: Keeper workflow

## Actions that will be executed on
on:  
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  
  # 
  # chek.yml workflow
  # Run everity time in this workflow and generate an output in case the test were sucessfully
  # 
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

